name: enable-pages-test
on:
  push:
    branches: [main]
  workflow_dispatch: {}
permissions:
  pages: write
jobs:
  enable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/configure-pages@v5
        with:
          enablement: true
